"""
soccerdata_sync.py
==================
Backend-driven data collection using the `soccerdata` Python library.

Replaces browser-extension scraping for:
  - FBref  → fixtures, team squad stats, player stats
  - ClubElo → team ELO ratings + upcoming fixture probabilities
    (fetched directly from api.clubelo.com — soccerdata's ClubElo class
     does not expose the Fixtures probability endpoint)

ALL existing _insert_* helpers from sync.py are reused unchanged.
ClubElo inserts reuse the same logic already in sync_enrichment.py.

Endpoints added (all require admin auth):
  POST /api/soccerdata/sync-league   – sync one league+season
  POST /api/soccerdata/sync-clubelo  – sync ClubElo fixture probabilities
  POST /api/soccerdata/sync-all      – background sync of every configured league

Nothing in sync.py, sync_enrichment.py, or main.py (beyond the router
registration) is altered by this file.
"""

from __future__ import annotations

import csv
import io
import json
import logging
import os
import pathlib
import shutil
import subprocess
import threading
from typing import Any, Optional

import httpx
import pandas as pd
from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException
from pydantic import BaseModel

from database import get_connection
from routes.deps import require_admin

# ── Reuse insert helpers from sync.py ─────────────────────────────────────────
# NOTE: _insert_standings and _insert_home_away_stats are intentionally NOT
# imported here.  soccerdata's FBref class has no standings or home/away
# endpoints — those data types are only produced by the browser extension
# (via sync.py's detect_table_type dispatch).  Importing them here would be
# dead code and misleading.
from routes.sync import (
    _auto_evaluate_predictions,
    _auto_recalibrate_bg,
    _insert_fixtures,
    _insert_player_stats,
    _insert_squad_stats,
    get_or_create_league,
    get_or_create_season,
    log_scrape,
    safe_num,
)

# ── Reuse team/league resolvers from sync_enrichment ──────────────────────────
# NOTE: CLUBELO_LEAGUE_MAP and TEAM_NAME_ALIASES are intentionally NOT imported
# here.  They are used inside _get_league() and _get_team() (defined in
# sync_enrichment.py) and do not need to be re-imported into this module.
from routes.sync_enrichment import (
    _get_league,
    _get_team,
)

logger = logging.getLogger(__name__)
router = APIRouter()


# ─────────────────────────────────────────────────────────────────────────────
# League / season name mappings
# ─────────────────────────────────────────────────────────────────────────────

# Canonical DB name → soccerdata league identifier
#
# IMPORTANT: soccerdata's FBref class only supports 5 leagues out of the box:
#   ENG-Premier League, ESP-La Liga, FRA-Ligue 1, GER-Bundesliga, ITA-Serie A
#
# All other leagues MUST be added via a league_dict.json config file placed at:
#   ~/soccerdata/config/league_dict.json   (Linux/Mac)
#   C:\Users\<you>\soccerdata\config\league_dict.json  (Windows)
#
# See EXTENDED_LEAGUES below and the league_dict.json file generated by
# _ensure_league_dict() for the extra mappings required at runtime.
# Without that file, any non-Big-5 league will raise a ValueError from soccerdata.
#
# Big-5 leagues — natively supported, no config file required:
CANONICAL_TO_SD: dict[str, str] = {
    "Premier League":   "ENG-Premier League",
    "Bundesliga":       "GER-Bundesliga",
    "La Liga":          "ESP-La Liga",
    "Serie A":          "ITA-Serie A",
    "Ligue 1":          "FRA-Ligue 1",
}

# Extended leagues — only work when league_dict.json is present (see below).
# Keys match CANONICAL_TO_SD format; values are the soccerdata identifiers.
# These are NOT included in CANONICAL_TO_SD directly to avoid silent runtime
# errors when the config file is missing.
EXTENDED_LEAGUES: dict[str, str] = {
    # English
    "Championship":                 "ENG-Championship",
    "League One":                   "ENG-League One",
    "League Two":                   "ENG-League Two",
    # German
    "2. Bundesliga":                "GER-2. Bundesliga",
    # Spanish
    "Segunda Division":             "ESP-Segunda División",
    # Italian
    "Serie B":                      "ITA-Serie B",
    # French
    "Ligue 2":                      "FRA-Ligue 2",
    # Dutch
    "Eredivisie":                   "NED-Eredivisie",
    # Belgian
    "Belgian Pro League":           "BEL-First Division A",
    # Turkish
    "Super Lig":                    "TUR-Süper Lig",
    # Scottish
    "Scottish Premiership":         "SCO-Premiership",
    # Portuguese
    "Primeira Liga":                "POR-Primeira Liga",
    # Austrian
    "Austrian Bundesliga":          "AUT-Bundesliga",
    # Greek
    "Greek Super League":           "GRE-Super League",
    # American
    "MLS":                          "USA-MLS",
    # South American
    "Brasileirao Serie A":          "BRA-Série A",
    "Argentine Primera Division":   "ARG-Primera División",
    # Asian
    "J1 League":                    "JPN-J1 League",
    # European competitions
    "UEFA Champions League":        "INT-Champions League",
    "UEFA Europa League":           "INT-Europa League",
    "UEFA Conference League":       "INT-Conference League",
    # Nordic
    "Danish Superliga":             "DEN-Superliga",
    "Norwegian Eliteserien":        "NOR-Eliteserien",
    "Swedish Allsvenskan":          "SWE-Allsvenskan",
    # Swiss
    "Swiss Super League":           "SUI-Super League",
    # Eastern European
    "Polish Ekstraklasa":           "POL-Ekstraklasa",
    # ── Extension-scraped leagues added below ──────────────────────────────
    # These leagues appear in url_manager.js DEFAULT_URLS but were missing
    # from the original CANONICAL_TO_SD map.
    "Bulgarian First League":       "BUL-First League",
    "Croatian Football League":     "CRO-HNL",
    "Czech First League":           "CZE-First League",
    "Hungarian OTP Bank Liga":      "HUN-OTP Bank Liga",
    "Israeli Premier League":       "ISR-Premier League",
    "Romanian Liga I":              "ROU-Liga I",
    "Serbian SuperLiga":            "SRB-SuperLiga",
    "Slovenian PrvaLiga":           "SVN-PrvaLiga",
    "Ukrainian Premier League":     "UKR-Premier League",
}

# Combined map used for validation and the /leagues endpoint.
# At runtime, _ensure_league_dict() must be called before using any EXTENDED league.
ALL_LEAGUES: dict[str, str] = {**CANONICAL_TO_SD, **EXTENDED_LEAGUES}


def _ensure_league_dict() -> None:
    """
    Write ~/soccerdata/config/league_dict.json with all FBref mappings for
    EXTENDED_LEAGUES if the file does not already exist.

    This is required because soccerdata only ships with the Big-5 leagues.
    The FBref internal identifier for each league is the table name used in
    the FBref URL, e.g. for Eredivisie: https://fbref.com/en/comps/23/…
    The mapping format follows soccerdata's league_dict.json schema.

    Call once at startup (or before the first sync of a non-Big-5 league).
    """
    soccerdata_dir = pathlib.Path(
        os.environ.get("SOCCERDATA_DIR", pathlib.Path.home() / "soccerdata")
    )
    config_dir = soccerdata_dir / "config"
    config_dir.mkdir(parents=True, exist_ok=True)
    league_dict_path = config_dir / "league_dict.json"

    if league_dict_path.exists():
        return  # already written — don't overwrite user customisations

    # FBref internal name = the string that appears in FBref league-table URLs.
    # e.g. https://fbref.com/en/comps/10/Championship-Stats → "Championship"
    # Derived from url_manager.js DEFAULT_URLS comp IDs.
    FBREF_INTERNAL: dict[str, str] = {
        # English
        "ENG-Championship":         "Championship",
        "ENG-League One":           "League One",
        "ENG-League Two":           "League Two",
        # German
        "GER-2. Bundesliga":        "2. Bundesliga",
        # Spanish
        "ESP-Segunda División":     "Segunda División",
        # Italian
        "ITA-Serie B":              "Serie B",
        # French
        "FRA-Ligue 2":              "Ligue 2",
        # Dutch
        "NED-Eredivisie":           "Eredivisie",
        # Belgian
        "BEL-First Division A":     "Belgian First Division A",
        # Turkish
        "TUR-Süper Lig":            "Süper Lig",
        # Scottish
        "SCO-Premiership":          "Scottish Premiership",
        # Portuguese
        "POR-Primeira Liga":        "Primeira Liga",
        # Austrian
        "AUT-Bundesliga":           "Austrian Football Bundesliga",
        # Greek  (comp/27 → Super-League-Greece-1)
        "GRE-Super League":         "Super League Greece 1",
        # American
        "USA-MLS":                  "Major League Soccer",
        # South American
        "BRA-Série A":              "Série A",
        "ARG-Primera División":     "Primera División",
        # Asian
        "JPN-J1 League":            "J1 League",
        # European competitions
        "INT-Champions League":     "Champions League",
        "INT-Europa League":        "Europa League",
        "INT-Conference League":    "UEFA Europa Conference League",
        # Nordic
        "DEN-Superliga":            "Danish Superliga",
        "NOR-Eliteserien":          "Eliteserien",
        "SWE-Allsvenskan":          "Allsvenskan",
        # Swiss
        "SUI-Super League":         "Super League",
        # Eastern European
        "POL-Ekstraklasa":          "Ekstraklasa",
        # ── Extension-scraped leagues (comp IDs from url_manager.js) ──────
        "BUL-First League":         "Bulgarian First League",     # comp/67
        "CRO-HNL":                  "Hrvatska NL",                # comp/63
        "CZE-First League":         "Czech First League",         # comp/66
        "HUN-OTP Bank Liga":        "NB I",                       # comp/46
        "ISR-Premier League":       "Israeli Premier League",     # comp/85
        "ROU-Liga I":               "Liga I",                     # comp/47
        "SRB-SuperLiga":            "Serbian SuperLiga",          # comp/65
        "SVN-PrvaLiga":             "Slovenian PrvaLiga",         # comp/69
        "UKR-Premier League":       "Ukrainian Premier League",   # comp/39
    }

    league_dict: dict[str, dict] = {}
    for sd_id, fbref_name in FBREF_INTERNAL.items():
        league_dict[sd_id] = {"FBref": fbref_name}

    with open(league_dict_path, "w", encoding="utf-8") as f:
        json.dump(league_dict, f, ensure_ascii=False, indent=2)

    logger.info("soccerdata league_dict.json written to %s", league_dict_path)


# All leagues that will be synced by sync-all (Big-5 + extended)
ALL_CONFIGURED_LEAGUES = list(ALL_LEAGUES.keys())


def _canonical_season(s: str) -> str:
    """Convert '2024-2025' → '2024-25' for soccerdata. Pass-through if already short."""
    if len(s) == 9 and s[4] == "-" and s[5:].isdigit():
        return f"{s[:4]}-{s[7:]}"
    return s  # already "2024-25" or single-year "2024"


def _find_chrome_binary() -> Optional[str]:
    """
    Locate the Chrome/Chromium binary on the current system.

    Search order:
      1. CHROME_BIN / CHROMIUM_BIN env vars — resolved via shutil.which if
         the value is a bare name (e.g. "chromium") rather than an absolute path.
      2. shutil.which() for common binary names (covers Nixpacks PATH symlinks).
      3. Common hard-coded absolute paths (/usr/bin/chromium, etc.).
      4. subprocess `which` as a last resort (resolves Nix store symlinks that
         shutil.which misses when the Nix profile isn't fully on PATH).

    Returns the resolved absolute path as a string, or None if nothing is found.
    """
    def _resolve(val: str) -> Optional[str]:
        """Return absolute path if val is an existing file, or resolve via which."""
        p = pathlib.Path(val)
        if p.is_absolute() and p.exists():
            return str(p)
        # bare name like "chromium" — resolve through PATH
        resolved = shutil.which(val)
        if resolved and pathlib.Path(resolved).exists():
            return resolved
        return None

    # 1: explicit env overrides
    for env_var in ("CHROME_BIN", "CHROMIUM_BIN"):
        val = os.environ.get(env_var, "").strip()
        if val:
            result = _resolve(val)
            if result:
                logger.info("Chrome binary from env %s: %s", env_var, result)
                return result
            logger.warning(
                "Env var %s=%r set but binary not found; continuing search.", env_var, val
            )

    # 2: shutil.which covers binaries on PATH (including Nixpacks wrapper symlinks)
    for name in ("chromium", "chromium-browser", "google-chrome", "google-chrome-stable"):
        found = shutil.which(name)
        if found and pathlib.Path(found).exists():
            logger.info("Chrome binary via which('%s'): %s", name, found)
            return found

    # 3: hard-coded fallback absolute paths
    for candidate in (
        "/usr/bin/chromium",
        "/usr/bin/chromium-browser",
        "/usr/bin/google-chrome",
        "/usr/bin/google-chrome-stable",
        "/usr/local/bin/chromium",
        "/usr/local/bin/google-chrome",
    ):
        if pathlib.Path(candidate).exists():
            logger.info("Chrome binary at hard-coded path: %s", candidate)
            return candidate

    # 4: subprocess `which` as last resort (handles Nix store symlinks that
    #    shutil.which misses when the Nix profile isn't fully on PATH)
    for name in ("chromium", "chromium-browser", "google-chrome"):
        try:
            resolved = subprocess.check_output(
                ["which", name], text=True, stderr=subprocess.DEVNULL
            ).strip()
            if resolved and pathlib.Path(resolved).exists():
                logger.info("Chrome binary via subprocess which('%s'): %s", name, resolved)
                return resolved
        except Exception:
            pass

    # 5: Manually search the Nix store for Railway Nixpacks deployments
    try:
        nix_store = pathlib.Path("/nix/store")
        if nix_store.exists():
            for p in nix_store.glob("*-chromium-*/bin/chromium"):
                if p.exists() and p.is_file():
                    logger.info("Chrome binary found via Nix store glob: %s", str(p))
                    return str(p)
    except Exception as e:
        logger.warning("Error searching Nix store: %s", e)

    return None


# ─────────────────────────────────────────────────────────────────────────────
# Pandas / soccerdata helpers
# ─────────────────────────────────────────────────────────────────────────────

_DOW_MAP = {
    "Mon": 1, "Tue": 2, "Wed": 3, "Thu": 4,
    "Fri": 5, "Sat": 6, "Sun": 7,
}


def _val(row: dict, *keys, default=None):
    """Return the first non-None value found under any of the given keys."""
    for k in keys:
        v = row.get(k)
        if v is not None and str(v).strip() not in ("", "nan", "NaT", "None"):
            return v
    return default


def _flatten_df(df: pd.DataFrame) -> pd.DataFrame:
    """Flatten multi-level column headers produced by soccerdata for stat tables."""
    if isinstance(df.columns, pd.MultiIndex):
        df = df.copy()
        df.columns = [
            "_".join(str(c) for c in col if str(c) not in ("", "nan")).lower()
            for col in df.columns
        ]
    else:
        df = df.copy()
        df.columns = [str(c).lower() for c in df.columns]
    return df


def _df_to_records(df: pd.DataFrame) -> list[dict]:
    """Reset index, flatten columns, replace NaN with None, return list of dicts."""
    df = df.reset_index()
    df = _flatten_df(df)
    df = df.where(pd.notna(df), None)
    return df.to_dict("records")


# ─────────────────────────────────────────────────────────────────────────────
# Conversion: soccerdata → existing insert-function format
# ─────────────────────────────────────────────────────────────────────────────

def _schedule_rows_to_fixtures(records: list[dict]) -> list[dict]:
    """
    Convert soccerdata FBref schedule records to the dict format that
    _insert_fixtures() already understands.
    """
    out = []
    for r in records:
        home = str(_val(r, "home_team", "home") or "").strip()
        away = str(_val(r, "away_team", "away") or "").strip()
        if not home or not away:
            continue

        h_goals = _val(r, "home_goals", "score_home")
        a_goals = _val(r, "away_goals", "score_away")
        try:
            score_str = f"{int(h_goals)}–{int(a_goals)}" if (h_goals is not None and a_goals is not None) else ""
        except (ValueError, TypeError):
            score_str = ""

        day_raw = str(_val(r, "day", "") or "")[:3].capitalize()
        round_val = _val(r, "round", "gameweek", "wk")

        out.append({
            "home_team":  home,
            "away_team":  away,
            "date":       str(_val(r, "date", "") or ""),
            "start_time": str(_val(r, "time", "start_time", "") or "") or None,
            "score":      score_str,
            "gameweek":   safe_num(round_val),
            "dayofweek":  _DOW_MAP.get(day_raw),
            "venue":      str(_val(r, "venue", "") or "").strip(),
            "attendance": safe_num(_val(r, "attendance")),
            "referee":    str(_val(r, "referee", "") or "").strip(),
            "round":      str(round_val or "").strip(),
        })
    return out


def _team_stat_rows_to_squad_stats(records: list[dict]) -> list[dict]:
    """
    Convert soccerdata FBref team-season-stats records to the dict format
    that _insert_squad_stats() already understands.

    soccerdata uses the same FBref data-stat attribute names that sync.py
    already handles (players_used, avg_age, possession, games, …).
    Extra columns are forwarded as standard_stats JSON.
    """
    CORE = {"league", "league_id", "season", "team", "squad",
            "players_used", "avg_age", "possession", "games", "games_starts",
            "minutes", "minutes_90s", "goals", "assists"}
    out = []
    for r in records:
        team = str(_val(r, "team", "squad") or "").strip()
        if not team or team.lower() in ("squad", "team", ""):
            continue

        extra = {k: v for k, v in r.items() if k not in CORE and v is not None}
        out.append({
            "team":           team,
            "players_used":   _val(r, "players_used"),
            "avg_age":        _val(r, "avg_age"),
            "possession":     _val(r, "possession"),
            "games":          _val(r, "games", "mp"),
            "games_starts":   _val(r, "games_starts", "starts"),
            "minutes":        _val(r, "minutes", "min"),
            "minutes_90s":    _val(r, "minutes_90s", "90s"),
            "goals":          _val(r, "goals", "gls"),
            "assists":        _val(r, "assists", "ast"),
            "standard_stats": extra,
        })
    return out


def _player_stat_rows_to_player_stats(records: list[dict]) -> list[dict]:
    """
    Convert soccerdata FBref player-season-stats records to the dict format
    that _insert_player_stats() already understands.
    """
    CORE = {"league", "league_id", "season", "player", "team", "squad",
            "nationality", "nation", "position", "pos", "age", "born",
            "games", "games_starts", "minutes", "minutes_90s", "goals", "assists"}
    out = []
    for r in records:
        name = str(_val(r, "player") or "").strip()
        if not name or name.lower() in ("player", ""):
            continue

        raw_nat = str(_val(r, "nationality", "nation") or "").strip()
        nationality = raw_nat.split()[-1] if raw_nat else ""

        extra = {k: v for k, v in r.items() if k not in CORE and v is not None}
        out.append({
            "player":         name,
            "nationality":    nationality[:10],
            "position":       str(_val(r, "position", "pos") or "")[:20],
            "team":           str(_val(r, "team", "squad") or "").strip(),
            "age":            safe_num(_val(r, "age")),
            "birth_year":     safe_num(_val(r, "born", "birth_year")),
            "games":          safe_num(_val(r, "games", "mp")),
            "games_starts":   safe_num(_val(r, "games_starts", "starts")),
            "minutes":        safe_num(_val(r, "minutes", "min")),
            "minutes_90s":    safe_num(_val(r, "minutes_90s", "90s")),
            "goals":          safe_num(_val(r, "goals", "gls")),
            "assists":        safe_num(_val(r, "assists", "ast")),
            "standard_stats": extra,
        })
    return out


# ─────────────────────────────────────────────────────────────────────────────
# ClubElo: direct fetch from api.clubelo.com (fixture probabilities)
# ─────────────────────────────────────────────────────────────────────────────

CLUBELO_FIXTURES_URL = "http://api.clubelo.com/Fixtures"


def _fetch_clubelo_fixtures() -> list[dict]:
    """
    Fetch upcoming fixture probabilities from api.clubelo.com/Fixtures.
    Returns a list of dicts matching what sync_enrichment's clubelo insert
    logic already expects (keys: Home, Away, League, Date, Home_Elo, Away_Elo,
    plus the probability columns stored as raw_data).
    """
    response = httpx.get(CLUBELO_FIXTURES_URL, timeout=30)
    response.raise_for_status()

    reader = csv.DictReader(io.StringIO(response.text))
    rows = []
    for row in reader:
        rows.append({
            "League": row.get("League", ""),
            "raw": {
                "Home":     row.get("HomeTeam", row.get("Home", "")),
                "Away":     row.get("AwayTeam", row.get("Away", "")),
                "Date":     row.get("Date", ""),
                "Home_Elo": row.get("Home", ""),
                "Away_Elo": row.get("Away", ""),
                **row,
            },
        })
    return rows


def _insert_clubelo_rows(cur, rows: list[dict]) -> int:
    """
    Insert ClubElo fixture rows into team_clubelo.

    Uses the same league-resolution strategy as sync_enrichment.py:
    look up each team's REAL league from the teams table rather than
    trusting ClubElo's country code (which uses ENG for ALL English
    divisions, causing Premier League / Championship / League One /
    League Two to be mixed).
    """
    from routes.sync_enrichment import _normalize_team_name, _strip_affixes
    count = 0
    for row in rows:
        raw = row.get("raw", row)
        home = raw.get("Home") or raw.get("HomeTeam")
        away = raw.get("Away") or raw.get("AwayTeam")
        target_date = raw.get("Date")

        if not home or not away or not target_date:
            continue

        home_elo = safe_num(raw.get("Home_Elo") or raw.get("Home_Prob"))
        away_elo = safe_num(raw.get("Away_Elo") or raw.get("Away_Prob"))

        for team_name, elo_val in [(home, home_elo), (away, away_elo)]:
            if not team_name:
                continue

            clean = _normalize_team_name(team_name)
            cur.execute(
                "SELECT id FROM teams WHERE name ILIKE %s LIMIT 1",
                (clean,)
            )
            team_row = cur.fetchone()

            if not team_row:
                stripped = _strip_affixes(clean)
                if stripped and stripped != clean.lower():
                    cur.execute(
                        "SELECT id FROM teams WHERE name ILIKE %s LIMIT 1",
                        (f"%{stripped}%",)
                    )
                    team_row = cur.fetchone()

            if not team_row:
                logger.debug("ClubElo: team %r not found in DB, skipping", clean)
                continue

            t_id = team_row["id"]
            cur.execute(
                """
                INSERT INTO team_clubelo (team_id, elo_date, elo, raw_data)
                VALUES (%s, %s, %s, %s)
                ON CONFLICT (team_id, elo_date) DO UPDATE SET
                    elo      = EXCLUDED.elo,
                    raw_data = EXCLUDED.raw_data,
                    scraped_at = NOW()
                """,
                (t_id, target_date, elo_val, json.dumps(row)),
            )
            count += 1
    return count


# ─────────────────────────────────────────────────────────────────────────────
# Request / response models
# ─────────────────────────────────────────────────────────────────────────────

class SoccerdataSyncRequest(BaseModel):
    """Sync a single league+season from FBref via soccerdata."""
    league: str                          # Canonical DB name, e.g. "Premier League"
    season: str                          # e.g. "2024-2025"
    data_types: Optional[list[str]] = [  # Which data to fetch
        "fixtures",
        "stats",
        "player_stats",
    ]


class SoccerdataSyncAllRequest(BaseModel):
    season: str                          # e.g. "2024-2025"
    leagues: Optional[list[str]] = None  # None = all configured leagues
    data_types: Optional[list[str]] = ["fixtures", "stats", "player_stats"]


# ─────────────────────────────────────────────────────────────────────────────
# Core sync logic
# ─────────────────────────────────────────────────────────────────────────────

def _do_sync_league(
    league_canonical: str,
    season_canonical: str,
    data_types: list[str],
) -> dict[str, Any]:
    """
    Pull data from FBref via soccerdata and write it to the database.
    Reuses all existing _insert_* functions so DB behaviour is identical
    to what the extension produces.
    """
    try:
        import soccerdata as sd  # imported lazily so the server starts without it
    except ImportError:
        raise RuntimeError(
            "soccerdata is not installed. "
            "Add 'soccerdata>=1.7' to requirements.txt and redeploy."
        )

    sd_league = ALL_LEAGUES.get(league_canonical)
    if not sd_league:
        raise ValueError(
            f"League '{league_canonical}' not in known leagues map. "
            f"Known leagues: {sorted(ALL_LEAGUES)}"
        )

    # Write league_dict.json if missing so non-Big-5 leagues are recognised
    _ensure_league_dict()

    sd_season = _canonical_season(season_canonical)
    logger.info(
        "soccerdata sync: league=%s sd=%s season=%s types=%s",
        league_canonical, sd_league, sd_season, data_types,
    )

    # Locate Chrome/Chromium binary for the Railway/Nixpacks environment
    chrome_bin = _find_chrome_binary()
    if not chrome_bin:
        raise RuntimeError(
            "No Chrome/Chromium binary found on this server. "
            "Ensure 'chromium' is listed in nixpacks.toml nixPkgs and/or "
            "set the CHROME_BIN environment variable to its full path."
        )
    logger.info("Using Chrome binary: %s", chrome_bin)

    fbref = sd.FBref(
        leagues=[sd_league],
        seasons=[sd_season],
        path_to_browser=chrome_bin,  # str, not Path — seleniumbase requires it
        headless=True,
    )

    fixtures_inserted = stats_inserted = players_inserted = 0

    conn = get_connection()
    cur = conn.cursor()
    try:
        league_id = get_or_create_league(cur, league_canonical)
        season_id = get_or_create_season(cur, season_canonical)

        # ── Fixtures ─────────────────────────────────────────────────────────
        if "fixtures" in data_types:
            try:
                df = fbref.read_schedule()
                records = _df_to_records(df)
                fixture_dicts = _schedule_rows_to_fixtures(records)
                fixtures_inserted = _insert_fixtures(
                    cur, league_id, season_id, league_canonical, fixture_dicts
                )
                logger.info("Fixtures inserted: %d", fixtures_inserted)
            except Exception as exc:
                logger.warning(
                    "Fixtures fetch failed for %s %s: %s",
                    league_canonical, sd_season, exc,
                )

        # ── Team squad stats ─────────────────────────────────────────────────
        if "stats" in data_types:
            for stat_type in ("standard", "shooting", "defense", "passing",
                              "possession", "keeper"):
                try:
                    df = fbref.read_team_season_stats(stat_type=stat_type)
                    records = _df_to_records(df)
                    squad_dicts = _team_stat_rows_to_squad_stats(records)
                    n = _insert_squad_stats(cur, league_id, season_id, squad_dicts)
                    stats_inserted += n
                    logger.info("Squad stats [%s] inserted: %d", stat_type, n)
                except Exception as exc:
                    logger.warning(
                        "Squad stats [%s] failed for %s %s: %s",
                        stat_type, league_canonical, sd_season, exc,
                    )

        # ── Player stats ─────────────────────────────────────────────────────
        if "player_stats" in data_types:
            try:
                df = fbref.read_player_season_stats(stat_type="standard")
                records = _df_to_records(df)
                player_dicts = _player_stat_rows_to_player_stats(records)
                players_inserted = _insert_player_stats(
                    cur, league_id, season_id, player_dicts
                )
                logger.info("Player stats inserted: %d", players_inserted)
            except Exception as exc:
                logger.warning(
                    "Player stats failed for %s %s: %s",
                    league_canonical, sd_season, exc,
                )

        total = fixtures_inserted + stats_inserted + players_inserted
        if total == 0:
            conn.rollback()
            return {
                "success": False,
                "warning": "empty_payload",
                "detail": "soccerdata returned no rows. Possibly rate-limited by FBref.",
                "league": league_canonical,
                "season": season_canonical,
            }

        conn.commit()
        log_scrape(cur, league_id, season_id, "soccerdata_sync", total, 0)
        conn.commit()

        evaluated = _auto_evaluate_predictions(conn)
        if evaluated > 0:
            threading.Thread(
                target=_auto_recalibrate_bg, daemon=True, name="sd-recalibrate"
            ).start()

        return {
            "success": True,
            "league": league_canonical,
            "season": season_canonical,
            "fixtures_inserted": fixtures_inserted,
            "stats_inserted": stats_inserted,
            "players_inserted": players_inserted,
            "predictions_evaluated": evaluated,
            "recalibration_triggered": evaluated > 0,
        }

    except Exception as exc:
        conn.rollback()
        logger.error(
            "soccerdata sync error [%s %s]: %s",
            league_canonical, season_canonical, exc,
            exc_info=True,
        )
        raise
    finally:
        conn.close()


# ─────────────────────────────────────────────────────────────────────────────
# Route handlers
# ─────────────────────────────────────────────────────────────────────────────

@router.post("/sync-league")
def sync_league(
    req: SoccerdataSyncRequest,
    _admin: dict = Depends(require_admin),
):
    """
    Sync a single league+season from FBref via soccerdata.

    Example body:
        {"league": "Premier League", "season": "2024-2025",
         "data_types": ["fixtures", "stats", "player_stats"]}
    """
    try:
        return _do_sync_league(req.league, req.season, req.data_types or [])
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except RuntimeError as exc:
        raise HTTPException(status_code=503, detail=str(exc))
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


@router.post("/sync-clubelo")
def sync_clubelo(_admin: dict = Depends(require_admin)):
    """
    Fetch upcoming fixture ELO probabilities from api.clubelo.com/Fixtures
    and store them in team_clubelo — identical to what the browser extension
    does, but triggered from the backend.
    """
    conn = get_connection()
    cur = conn.cursor()
    try:
        rows = _fetch_clubelo_fixtures()
        inserted = _insert_clubelo_rows(cur, rows)
        conn.commit()
        return {"success": True, "team_clubelo_inserted": inserted}
    except httpx.HTTPError as exc:
        conn.rollback()
        raise HTTPException(status_code=502,
                            detail=f"ClubElo API unreachable: {exc}")
    except Exception as exc:
        conn.rollback()
        raise HTTPException(status_code=500, detail=str(exc))
    finally:
        conn.close()


def _sync_all_bg(
    leagues: list[str],
    season: str,
    data_types: list[str],
) -> None:
    """Background task: iterate through leagues sequentially."""
    for league in leagues:
        try:
            result = _do_sync_league(league, season, data_types)
            logger.info("sync-all [%s]: %s", league, result)
        except Exception as exc:
            logger.error("sync-all [%s] failed: %s", league, exc, exc_info=True)


@router.post("/sync-all")
def sync_all(
    req: SoccerdataSyncAllRequest,
    background_tasks: BackgroundTasks,
    _admin: dict = Depends(require_admin),
):
    """
    Kick off a background sync for every configured league (or a subset).
    Returns immediately; progress is visible in server logs.

    Example body:
        {"season": "2024-2025"}
        {"season": "2024-2025", "leagues": ["Premier League", "Bundesliga"]}
    """
    leagues = req.leagues or ALL_CONFIGURED_LEAGUES
    unknown = [lg for lg in leagues if lg not in ALL_LEAGUES]
    if unknown:
        raise HTTPException(
            status_code=400,
            detail=f"Unknown leagues (not in supported leagues map): {unknown}",
        )

    data_types = req.data_types or ["fixtures", "stats", "player_stats"]
    background_tasks.add_task(_sync_all_bg, leagues, req.season, data_types)
    return {
        "success": True,
        "message": f"Background sync started for {len(leagues)} league(s)",
        "leagues": leagues,
        "season": req.season,
        "data_types": data_types,
    }


@router.get("/leagues")
def list_supported_leagues(_admin: dict = Depends(require_admin)):
    """Return the list of leagues supported by the soccerdata sync.

    'native' leagues work out of the box. 'extended' leagues require the
    league_dict.json config file (auto-written on first sync attempt).
    """
    return {
        "leagues": [
            {
                "canonical": k,
                "soccerdata_id": v,
                "support": "native" if k in CANONICAL_TO_SD else "extended",
            }
            for k, v in sorted(ALL_LEAGUES.items())
        ]
    }
